### PR TITLE
Updated to v0.12.x

### PR DESCRIPTION
**Pull request by eviefp**
Updated to v0.12. No worries, I can use my fork if you're not maintaining/care about this anymore. The update really smooth, only changes needed were in the tests (mostly due to `Eff` going away for `Effect`).

### CODE REVIEW

**Comment by klangner** [comment]
Thank you for the PR. If you want me to upgrade, could you please fix CI so it builds correctly?

**Comment by eviefp** [comment]
Whoops, I did not notice the `travis` file there. I just had to update `bower.json` to import the correct updated libraries. Build passed now.

**Comment by klangner** [comment]
Thank you :-)

One question:
I haven't write in PureScript for some time so probably I'm missing something.
But what are those *.dhal files for?

**Comment by eviefp** [comment]
They are used for `spago` (https://github.com/spacchetti/spago), which is a new build tool that can be used instead of `pulp`. It's pretty neat and makes use of the nice things in the Dhall configuration language. I suppose they're not needed here, so I can remove them. I just added as I got used to `spago` more than `bower`. I actually think most libraries don't use `spago` so it doesn't make sense to have them here.

**Pull request merged**
